spring:
  application:
    name: platform-api
  http:
    encoding:
      charset: UTF-8
      force: true
  jmx:
    default-domain: fr.project-factory.web.api
server:
  port: 8090
  contextPath: /api
management:
  contextPath: /management
security:
  user:
    name: root
    password: changeit
    role: USER,ADMIN
  oauth2:
    client:
      accessTokenUri: https://dev.project-factory.fr/cas/oauth2.0/accessToken
      userAuthorizationUri: https://dev.project-factory.fr/cas/oauth2.0/authorize
      clientId: localhost
      clientSecret: localhost
      clientAuthenticationScheme: query
      authenticationScheme: query
    resource:
      userInfoUri: https://dev.project-factory.fr/cas/oauth2.0/profile
      preferTokenInfo: false
logging:
  path: logs
  level:
    org.springframework.security.oauth2: debug
    fr.projectfactory.api: debug
authorization:
  userAttribute: "['id']"
  userAuthorityPrefix: USER_
  userAuthorityUppercase: false
  groupAttribute: "['attributes']?.get('groups')"
  groupAuthorityPrefix: GROUP_
  groupAuthorityUppercase: false
  authorityMapping:
    ROLE_USER: GROUP_pf-users
    ROLE_ADMIN: GROUP_pf-admins
ldap:
  contextSource:
    urls: ldap://localhost:10389
    base: dc=dev,dc=project-factory,dc=fr
    userDn: cn=root,dc=dev,dc=project-factory,dc=fr
    password: uTA1AwnQXK9Rc6WQ
