spring:
  application:
    name: platform-manager
  http:
    encoding:
      charset: UTF-8
      force: true
  jmx:
    default-domain: fr.project-factory.web.manager
  resources:
    cache-period: 600
server:
  port: 8091
  contextPath: /manager
management:
  contextPath: /management
security:
  user:
    name: root
    password: changeit
    role: USER,ADMIN
  oauth2:
    client:
      accessTokenUri: https://dev.project-factory.fr/cas/oauth2.0/accessToken
      userAuthorizationUri: https://dev.project-factory.fr/cas/oauth2.0/authorize
      clientId: localhost
      clientSecret: localhost
      clientAuthenticationScheme: query
      authenticationScheme: query
    resource:
      userInfoUri: https://dev.project-factory.fr/cas/oauth2.0/profile
      preferTokenInfo: false
    logout:
      userLogoutUri: https://dev.project-factory.fr/cas/logout
      redirectParam: service
      redirectUri: http://localhost:8091/manager/
logging:
  path: logs
  level:
    org.springframework.security.oauth2: debug
zuul:
  host:
    connect-timeout-millis: 5000
    socket-timeout-millis: 60000
  routes:
    api-v1:
      path: /v1/**
      url: http://localhost:8090/api/v1
